language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - 'pip install pytest pytest-cov'
  - 'pip install -r requirements.txt'
  - 'python setup.py install'
script:
  - 'pytest --cov-report=xml --cov=libevolve tests/'