language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - conda activate test

script:
  - git clone https://github.com/uniopt/libevolve.git
  - cd libevolve
  - python setup.py install
  - cd test
  - py.test
